- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes
      changed_when: False

    - name: Upgrade all packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes

    - name: Ensure ansible-pull log file exists
      file:
        path: /var/log/ansible-pull.log
        state: touch
        owner: ansible
        group: ansible
        mode: 0664

  tasks:
    - include: tasks/users.yml
    - include: tasks/logrotate.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
