- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes
      changed_when: False

    - name: Upgrade all packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes

  tasks:
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/logrotate.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/cron.yml
