- name: Create an ansible user to use with cron
  user:
    name: ansible
    system: yes

- name: Copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Ensure ansible-pull log file exists
  file:
    path: /var/log/ansible-pull.log
    state: touch
    owner: ansible
    group: ansible
    mode: 0664
